version: '3.8'
services:
  courses-service:
    build: ./hexya-ng/services/courses-service
    ports:
      - "8081:8081"
    networks:
      - hexya-ng-net
    dns:
      - 127.0.0.1

  sessions-service:
    build: ./hexya-ng/services/sessions-service
    ports:
      - "8082:8082"
    networks:
      - hexya-ng-net
    dns:
      - 127.0.0.1

  attendees-service:
    build: ./hexya-ng/services/attendees-service
    ports:
      - "8083:8083"
    networks:
      - hexya-ng-net
    dns:
      - 127.0.0.1

  api-gateway:
    build: ./hexya-ng/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - courses-service
      - sessions-service
      - attendees-service
    networks:
      - hexya-ng-net
    dns:
      - 127.0.0.1

networks:
  hexya-ng-net:
    driver: bridge
