// config/config.go
package config

import "github.com/hexya-erp/hexya/src/tools/generate/models"

const (
	// HexyaPath is the go import path of the base hexya package
	HexyaPath = "github.com/hexya-erp/hexya"
	// ModelsPath is the go import path of the hexya/models package
	ModelsPath = HexyaPath + "/src/models"
	// DatesPath is the go import path of the hexya/models/types/dates package
	DatesPath = HexyaPath + "/src/models/types/dates"
	// PoolPath is the go import path of the autogenerated pool package
	PoolPath = "github.com/hexya-erp/pool"
	// PoolModelPackage is the name of the pool package with model data
	PoolModelPackage = "h"
	// PoolQueryPackage is the name of the pool package with query data
	PoolQueryPackage = "q"
	// PoolInterfacesPackage is the name of the pool packages with all model interfaces
	PoolInterfacesPackage = "m"
	// Base is the PackageType for the base package of a module
	Base models.PackageType = iota
	// Models is the PackageType for the hexya/models package
	Models
	// TempEmpty is a temporary filename
	TempEmpty = "temp.go"
	// PoolDirRel is the relative directory for pool
	PoolDirRel = "pool"
	// ResDirRel is the relative directory for resources
	ResDirRel = "res"
)

var (
	// ModelMixins are the names of the mixins declared in the models package
	ModelMixins = map[string]bool{
		"CommonMixin":    true,
		"BaseMixin":      true,
		"ModelMixin":     true,
		"TransientMixin": true,
	}
	// ConditionFuncs are conditions used for models
	ConditionFuncs = []string{"And", "AndNot", "Or", "OrNot"}
	// SymlinkDirs are directories that should have symbolic links
	SymlinkDirs = []string{"static", "data", "demo", "resources", "i18n"}
)
