
= Installing Hexya
Author Nicolas Piganeau
:prewrap!:
:toc:
:sectnums:

== Introduction
Hexya is a modular ERP distributed as source code. The following instructions will guide you through downloading the source code, setting up your configuration, and compiling Hexya.

== Prerequisites

=== Install Go
Install the Go SDK from https://golang.org/dl/. Hexya requires Go 1.23 or later. Set up your Go workspace (default is `$HOME/go`). Add `$GOPATH/bin` to your `$PATH`.

[NOTE]
====
Hexya uses Go modules, so avoid working directly inside the Go workspace.
====

=== Install Sass
Hexya requires the Sass compiler. Install it with npm:

```
$ npm install -g sass
```

== Download

=== Download Hexya
Clone the Hexya repository:

[source,shell]
----
git clone https://github.com/hexya-erp/hexya.git
----

WARNING: Do **NOT** download Hexya inside your Go workspace.

Install Hexya with:

[source,shell]
----
cd path/to/hexya
go install
----

== Create a Project

=== Download Demo Project
If you want to evaluate Hexya, clone the demo project:

[source,shell]
----
git clone https://github.com/hexya-erp/hexya-demo.git
----

=== Create a Custom Project
To create a custom project, use the following command inside an empty directory:

[source,shell]
----
hexya project init github.com/myusername/myhexyaproject
----

This will generate `go.mod` and `hexya.toml` files in your project directory.

== Generate Hexya

Generate necessary source code:

[source,shell]
----
cd <projectDir>
hexya generate .
----

[NOTE]
====
Under Windows, run `hexya generate` as an administrator.
====

== Synchronize Database

=== Set Up PostgreSQL
Hexya currently supports PostgreSQL. Create a PostgreSQL user and database:

[source,shell]
----
sudo su - postgres -c "createuser -s $USER"
createdb hexya
----

=== Synchronize Database Schema
Synchronize the database schema with the models:

[source,shell]
----
cd <projectDir>
hexya updatedb -o
----

== Running Hexya

Start the Hexya server:

[source,shell]
----
cd <projectDir>
hexya server -o
----

Access the Hexya server at http://localhost:8080

Default credentials are:
- Login: `admin`
- Password: `admin`

For additional CLI parameters, refer to the link:cli.adoc[See CLI Documentation]

