package generate

import "text/template"

var poolGenericTemplate = template.Must(template.New("").Parse(`
// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package pool

import (
    "github.com/hexya-erp/hexya/src/models"
)

{{range .Models}}
// {{.Name}}Data is the data struct for the {{.Name}} model.
type {{.Name}}Data struct {
    *models.ModelData
    {{range .Fields}}
    {{.Name}} {{.Type}}
    {{end}}
}
{{end}}

func init() {
    {{range .Models}}
    models.NewModel("{{ .Name }}")
    {{end}}
}

{{range .Models}}
// {{.Name}} returns a ConditionStart for the {{.Name}} model.
func {{.Name}}() models.GenericConditionStart[{{.Name}}Data] {
    return models.GenericConditionStart[{{.Name}}Data]{
        ConditionStart: models.NewCondition().And(),
    }
}
{{end}}
`))
